import argparse
import logging
import importlib
import os
import sys
from datetime import datetime
from pathlib import Path
import yaml
from fuxictr.utils import set_logger
from fuxictr.features import FeatureMap
from fuxictr.pytorch.dataloaders import RankDataLoader

TRAINING_DIR = Path(__file__).parent.parent
DATASET_DIR = TRAINING_DIR.parent / "dataset"


def load_params(model_name, dataset_name="dataset"):
    with open(DATASET_DIR / f"{dataset_name}.yaml") as f:
        dataset_params = yaml.safe_load(f)
    with open(TRAINING_DIR / "train" / "train.yaml") as f:
        train_params = yaml.safe_load(f)
    with open(TRAINING_DIR / "models" / model_name / f"{model_name}.yaml") as f:
        model_params = yaml.safe_load(f)
    return {**dataset_params, **train_params, **model_params}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model",   required=True,      help="Modellname, z.B. AFN, DCNv2, FinalMLP, PNN")
    parser.add_argument("--dataset", default="dataset",  help="Dataset-Config (default: dataset, seq: dataset_seq)")
    args = parser.parse_args()

    params = load_params(args.model, args.dataset)
    # Unique model_id per run so logs and checkpoints don't overwrite each other
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    params["model_id"] = f"{args.model}_{timestamp}"
    set_logger(params)
    logging.info("Params: " + str(params))

    # Build FuxiCTR FeatureMap from the feature_map.json generated by preprocess/preprocess.py
    json_file = os.path.join(params["data_root"], params["dataset_id"], "feature_map.json")
    feature_map = FeatureMap(dataset_id=params["dataset_id"], data_dir=params["data_root"])
    feature_map.load(json_file, params)

    # Load train/validation data (expects .npz files generated by preprocess/preprocess.py)
    train_gen, valid_gen = RankDataLoader(
        feature_map,
        stage="train",
        train_data=params["train_data"],
        valid_data=params["valid_data"],
        batch_size=params["batch_size"],
        shuffle=params["shuffle"],
    ).make_iterator()

    # Dynamically load model class from models/<MODEL>/<MODEL>.py
    sys.path.insert(0, str(TRAINING_DIR / "models" / args.model))
    ModelClass = getattr(importlib.import_module(args.model), args.model)
    model = ModelClass(feature_map, **params)
    model.count_parameters()

    model.fit(train_gen, validation_data=valid_gen, epochs=params["epochs"])

    # Evaluate on held-out test set
    test_gen = RankDataLoader(
        feature_map,
        stage="test",
        test_data=params["test_data"],
        batch_size=params["batch_size"],
        shuffle=False,
    ).make_iterator()

    test_result = model.evaluate(test_gen)
    logging.info(f"Test-Ergebnis: {test_result}")
    print(f"\n=== Test-Ergebnis ===\n{test_result}")
    print(f"\nModell gespeichert in: {model.checkpoint}")


if __name__ == "__main__":
    main()
